### ISSUE TITLE
Creating a real fork of tasmota and adding the set of current changes to it

### ISSUE THREAD

**Issue by eckelj** [rddl-network/tasmota-firmware#17]
The plan is to publish a prop Tasmota fork in order to be able to integrate changes from the community and give back to the community,

Having that, we going to announce what've done.

**Comment by jmastr** [comment]
![Screenshot 2023-08-14 at 14 12 52](https://github.com/rddl-network/tasmota-firmware/assets/11860038/00f54a56-5497-4d88-95a4-9abf75c2e6b9)

Fork of https://github.com/arendst/Tasmota created under https://github.com/rddl-network/Tasmota:
- Development branch of https://github.com/rddl-network/tasmota-firmware pushed as `rddl-development`
- `rddl-development` branch set as default branch
- `#` in commit message were replaced by `rddl-network/tasmota-firmware#` to link to the correct repo and not spam the upstream repo from Tasmota (as you can see in the screenshot above taken at an earlier point in time)

**Comment by jmastr** [comment]
As agreed with @Cybnon this repo will be archived and thus set to read-only
